export type ModalId =
  | 'caravan-trade'
  | 'combat-orders'
  | 'hero-burst-skills'
  | 'hero-teachings'
  | 'loot-filters'
  | 'outpost-teleport'
  | 'reclass-heroes'
  | 'raid-defense'
  | 'town-materials'
  | 'trainer-visit'
  | 'exchange-node'
  | 'changelog'
  | 'pause-menu'
  | 'settings'
  | 'tasks';
