- id: cdd6110a-4b5f-42d8-9603-450492fabca1
  name: Cloak of Adventuring
  description: A cloak that is worn by beginning adventurers.
  sprite: '0000'

  baseStats:
    Defense: 1
    Agility: 1

  statsPerLevel: {}
