- id: 43282cd2-96e8-4590-b539-ff02f6db7ebf
  name: Attack
  description: Attack a single enemy, doing strong damage.

  rarity: Common
  sprite: '0000'

  epCost: 0
  usesPerCombat: -1

  statusEffectDurationBoost: {}
  statusEffectChanceBoost: {}

  techniques:
    - attributes: [DamagesTarget, AllowPlink, AllowLuckDodge]
      elements: []
      targets: 1
      targetType: Enemies
      targetBehaviors:
        - behavior: NotZeroHealth
      damageScaling:
        Strength: 1
      statusEffects: []
      combatMessage: '**{{ combatant.name }}** attacks **{{ target.name }}** for {{ damage }} damage ({{ target.hp }}/{{ target.totalStats.Health }} HP remaining).'
