import type { IconSize } from '@interfaces/artable';
import {
  gameAges,
  gameAngelWings,
  gameArmorDowngrade,
  gameBallGlow,
  gameBleedingWound,
  gameBodySwapping,
  gameBrain,
  gameBrokenHeart,
  gameChest,
  gameClockwork,
  gameClover,
  gameContract,
  gameCrossedSwords,
  gameCrown,
  gameCrystalBall,
  gameDeadlyStrike,
  gameDodging,
  gameDoubleRingedOrb,
  gameDrop,
  gameDuration,
  gameDustCloud,
  gameEarthWorm,
  gameEmerald,
  gameExitDoor,
  gameExtraTime,
  gameFlame,
  gameFog,
  gameGavel,
  gameGlassBall,
  gameGlassHeart,
  gameGooeyImpact,
  gameHeartBeats,
  gameHeatHaze,
  gameHelp,
  gameHolyGrail,
  gameHumanTarget,
  gameIceCube,
  gameKnockedOutStars,
  gameLava,
  gameMagicPotion,
  gameMagicShield,
  gameMedal,
  gameMedievalGate,
  gameMeepleGroup,
  gameOilySpiral,
  gameOpenBook,
  gamePauseButton,
  gamePlainCircle,
  gamePlayButton,
  gamePoison,
  gamePowder,
  gameSandstorm,
  gameSevenPointedStar,
  gameShieldReflect,
  gameSmallFire,
  gameSteam,
  gameStonePile,
  gameSwanBreeze,
  gameSwapBag,
  gameSwordBrandish,
  gameTargeted,
  gameTrophyCup,
  gameVibratingShield,
  gameWorld,
} from '@ng-icons/game-icons';
import {
  tablerCheck,
  tablerExclamationCircle,
  tablerFocus,
  tablerPlus,
  tablerSettings,
  tablerX,
} from '@ng-icons/tabler-icons';

export const ALL_ICONS = {
  gameExitDoor,
  gameHumanTarget,
  gameAges,
  gameGooeyImpact,
  gameGlassHeart,
  gameClockwork,
  gameVibratingShield,
  gameBrain,
  gameGavel,
  gameHeartBeats,
  gameDuration,
  gameDrop,
  gameClover,
  gamePauseButton,
  gamePlayButton,
  gameSmallFire,
  gameIceCube,
  gameSwanBreeze,
  gameStonePile,
  gamePlainCircle,
  gameSevenPointedStar,
  gameCrossedSwords,
  gameSwordBrandish,
  gameSwapBag,
  gameGlassBall,
  gameEmerald,
  gameDoubleRingedOrb,
  gameBallGlow,
  gameEarthWorm,
  gameMedievalGate,
  gameDustCloud,
  gameWorld,
  gameHelp,
  gameSandstorm,
  gameLava,
  gameHeatHaze,
  gameSteam,
  gamePowder,
  gameHolyGrail,
  gameOilySpiral,
  gameChest,
  gameCrystalBall,
  gameTrophyCup,
  gameOpenBook,
  gameMeepleGroup,
  gameBodySwapping,
  gameMagicPotion,
  gameContract,
  gameMedal,
  gameCrown,
  gameArmorDowngrade,
  gameBleedingWound,
  gamePoison,
  gameFlame,
  gameExtraTime,
  gameDeadlyStrike,
  gameFog,
  gameDodging,
  gameMagicShield,
  gameShieldReflect,
  gameBrokenHeart,
  gameAngelWings,
  gameKnockedOutStars,
  gameTargeted,
  tablerPlus,
  tablerSettings,
  tablerX,
  tablerCheck,
  tablerExclamationCircle,
  tablerFocus,
};

// Resolves `IconSize` tokens to their CSS value, used internally by `IconComponent`.
export const ICON_SIZE_VALUES: Record<IconSize, string> = {
  badge: '14px',
  inline: '1em',
  row: '1.2em',
  stat: '1.5em',
  nav: '2em',
};
