- id: 46aac966-48c0-4b4c-84ed-a371bb65acba
  name: Goblin
  description: The most common monster. It's mischevious and likes to steal things from adventurers.

  sprite: '0000'
  frames: 4

  targettingType: Random

  rarity: Common

  xp:
    min: 3
    max: 5
    multiplierPerLevel: 1

  droppedItems:
    - itemId: Gold Coin
      min: 3
      max: 10
      multiplierPerLevel: 1

  skills:
    - skillId: Attack

  baseStats:
    Health: 20
    Energy: 5
    Luck: 1
    Intelligence: 1
    Strength: 3
    Vitality: 2
    Resistance: 1
    Agility: 5

  statsPerLevel:
    Health: 2
    Energy: 0.5
    Luck: 0.05
    Intelligence: 0.1
    Strength: 0.3
    Vitality: 0.2
    Resistance: 0.1
    Agility: 0.3
