- id: 46aac966-48c0-4b4c-84ed-a371bb65acba
  name: Goblin
  description: The most common monster. It's mischevious and likes to steal things from adventurers.

  sprite: '0000'
  frames: 4

  baseStats:
    Health: 3
    Damage: 1

  statsPerLevel:
    Health: 0.2
    Damage: 0.05
