- id: a65a81d0-1be8-4ae4-8547-8b5008dbd407
  name: Copper Helm
  description: A duchy-made helm crafted from copper.
  levelRequirement: 4
  rarity: Uncommon
  type: Helm
  sprite: '0064'
  slots: 1
  baseStats:
    Health: 5
    Vitality: 2.5
